app_defaults: &app_defaults
  theme_advanced_buttons1: bold,italic,underline,separator,strikethrough,justifyleft,justifycenter,justifyright,justifyfull,bullist,numlist,undo,redo,link,unlink
  theme_advanced_buttons2: tablecontrols,separator,image
  extended_valid_elements: a[name|href|target|title|onclick],img[class|src|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name],hr[class|width|size|noshade],font[face|size|color|style],span[class|align|style]
  
development:
  <<: *app_defaults
  
test:
  <<: *app_defaults
    
production:
  <<: *app_defaults